name: pa11y tests

on:
  schedule:
    - cron: '15 15 * * *'
  workflow_dispatch:

jobs:
  build:
    name: Running pa11y-ci tests. 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source.
        uses: actions/checkout@v2

      - name: Install pa11y-ci dependencies.
        run: npm install

      - name: Run pa11y-ci.
        run: npm run pa11y-ci:sitemap

      - name: Display failure instructions.
        if: ${{ failure() }}
        run: |
          echo "::group::pa11y errors"
          echo "pa11y-ci found some accessibility problems, download 'pa11y_report' under artifacts to see the report."
          echo "::endgroup::"
      - name: Generate pa11y HTML report.
        if: ${{ always() }}
        run: npm run pa11y-ci:output
        
      - name: Commit pa11y HTML report.
        uses: EndBug/add-and-commit@v7

      - name: Save pa11y HTML report.
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: pa11y_report
          path: pa11y_report
